### ISSUE TITLE
How to configure YAML for nested javax.management.openmbean.CompositeData type?

### ISSUE THREAD

**Issue by KParzival** [DataDog/jmxfetch#129]
Migrating a bunch of hosts from current monitoring solution to Datadog, hit a snag when trying to format YAML for a nested CompositeData.

Example output from JTerm:

```
$>get LastSuccessfulRun
#mbean = mybean:type=test:
LastSuccessfulRun = {
  elapsedTime = 220;
  mapOutputRuntime = {
    records = 37901;
    runtime = 23463;
   };
  cellStats = {
    TypeFilter = {
      Data loader runtime (ms) = -1;
      Filter runtime (ms) = -1;
     };
    allDataLoadersRuntime = 6611;
    allFiltersRuntime = 83921;
   };
  domainLoadRuntimes = {
    ( APPLY_SETS ) = {
      name = APPLY_SETS;
      records = 11923;
      runtime = 12;
     };
    ( RIGHT_SITE ) = {
      name = RIGHT_SITE;
      records = 1612;
      runtime = 25;
     };
   };
 };
```

Several different layers represented in this snippet, the only thing here I have been successfully able to capture is   **elapsedTime = 220;**  This was done successfully using the formatting demonstrated here: https://github.com/DataDog/jmxfetch/blob/master/src/main/resources/jmx-2.yaml#L3-L14  

I tried adding another period (.) separator for the nested scenarios as shown below (as well as a few other variations), but it didn't seem to work.  Any advice would be appreciated, thanks.
```
    conf:
      - 
        include: 
          attribute:
            LastSuccessfulRun.mapOutputRuntime.records:
              alias: test.LastSuccessfulRune_mapOutputRuntime_records
              metric_type: gauge 
```
