### ISSUE TITLE
Incorrect name for G1GC old generation JMX metric

### ISSUE THREAD

**Issue by dpratt** [DataDog/jmxfetch#230]
The JMX metric name for collecting info on G1GC old generation counts and durations is incorrectly named. The default config file uses the name 'G1 Mixed Generation' when it should be 'G1 Old Generation'. I've confirmed this using visualvm on a running Java 8, 11 and 12 VM.

In the default config file (new-gc-default-jmx-metrics.yaml) the stanza at the bottom that reads

```yaml
- include:
    domain: java.lang
    type: GarbageCollector
    name: G1 Mixed Generation
    attribute:
      CollectionCount:
        alias: jvm.gc.major_collection_count
        metric_type: counter
      CollectionTime:
        alias: jvm.gc.major_collection_time
        metric_type: counter
```
should be
```yaml
- include:
    domain: java.lang
    type: GarbageCollector
    name: G1 Old Generation
    attribute:
      CollectionCount:
        alias: jvm.gc.major_collection_count
        metric_type: counter
      CollectionTime:
        alias: jvm.gc.major_collection_time
        metric_type: counter
```
