### ISSUE TITLE
Tags not applied to Metrics

### ISSUE THREAD

**Issue by jonathan-russo** [DataDog/jmxfetch#249]
Hi there,

We just started utilizing Datadog about a month ago and love the deep analysis into our application.  However one issue we are experiencing is the inability to associate custom tags with our JMX metrics.  The only tags we see for metrics reported by the JMX integration are attributes associated with that specific bean attribute.  Ex: The metric `hikaricp.connections.active` has the tag key `pool` associated with it.  We would like to see two tags, `env` and `service` tagged along with the JMX reporting.  Despite multiple attempts at configuring the proper jmx.d/conf.yaml file and a two week support ticket we cannot get any resolution here.  

Below are the details of our configuration:

Host Info:
```
bootTime: 2019-09-18 10:58:14.000000 UTC
kernelVersion: 4.14.138-114.102.amzn2.x86_64
os: linux
platform: amazon
platformFamily: rhel
platformVersion: 2
procs: 185
uptime: 6h31m39s
virtualizationRole: guest
virtualizationSystem: xen
```
Datadog agent version: `6.13.0`

datadog.yaml:
```api_key: xxxxxxxxx
tags:
  - env:production
  - service:appname
logs_enabled: true
apm_config:
  enabled: true
  ignore_resources: ["(GET|POST) /manage/health", "(GET|POST) .*security/ping.*"]
log_level: debug
```

jmx.d/conf.yaml:
```
init_config:
  is_jmx: true
  new_gc_metrics: true
instances:
  - host: localhost
    port: 1099
    tags:
      - env:production
      - service:appname
    conf:
      - include:
          domain: metrics
          bean_regex: .*cacheEvictions.*
          attribute:
            - OneMinuteRate
      - include:
          domain: metrics
          bean_regex: .*cacheGets.*
          attribute:
            - OneMinuteRate
      - include:
          domain: metrics
          bean_regex: .*cacheMisses.*
          attribute:
            - OneMinuteRate
      - include:
          domain: metrics
          bean_regex: .*cachePuts.*
          attribute:
            - OneMinuteRate
      - include:
          domain: metrics
          bean_regex: .*cacheSize.*
      - include:
          domain: metrics
          bean_regex: .*hikaricpConnectionsActive.*
      - include:
          domain: metrics
          bean_regex: .*hikaricpConnectionsIdle.*
      - include:
          domain: metrics
          bean_regex: .*jvmThreadsStates.*
      - include:
          domain: metrics
          bean_regex: .*tomcatThreadsBusy.*
      - include:
          domain: metrics
          bean_regex: .*tomcatThreadsCurrent.*
```
JMX section of the datadog-agent status:
```
========
JMXFetch
========

  Initialized checks
  ==================
    jmx
      instance_name : jmx-localhost-1099
      message :
      metric_count : 194
      service_check_count : 0
      status : OK
  Failed checks
  =============
    no checks
```

Any help would be greatly appreciated.  Let me know if you guys need any more information

**Comment by jonathan-russo** [comment]
If anybody is interested in this issue.  With help from the Datadog engineering team we were able to get a resolution on the issue.  We determined that all of the metrics collected by the jmx agent were being populated in the metric named: "jmx.metrics.value".  The "name" tag associated with that metric determined the actual metric(things like "hikaricpconnectionsidle.pool.hikaripool-1")

We were able to "alias" the metrics in our config file to come through with the proper metric name and are back in business.

**Comment by bkadatz** [comment]
Can you share what the alias setup looks like?

**Comment by jonathan-russo** [comment]
Sure.  Here you go.

```
init_config:
  is_jmx: true
  new_gc_metrics: true

instances:
  - host: localhost
    port: 1099
    tags:
      - env:production
      - service:appname
    conf:
      - include:
          domain: metrics
          bean_regex: .*cacheEvictions\.cache\.(.*)\.cacheManager\.cacheManager.*
          attribute:
            OneMinuteRate:
              alias: customjmx.cacheEvictions.OneMinuteRate
          tags:
            cache: $1
      - include:
          domain: metrics
          bean_regex: .*cacheGets\.cache\.(.*)\.cacheManager\.cacheManager\.name.*\.result\.(\w+)
          attribute:
            OneMinuteRate:
              alias: customjmx.cacheGets.OneMinuteRate
          tags:
            cache: $1
            result: $2
      - include:
          domain: metrics
          bean_regex: .*cacheMisses\.cache\.(.*)\.cacheManager\.cacheManager\.name.*\.reason\.(\w+)
          attribute:
            OneMinuteRate:
              alias: customjmx.cacheMisses.OneMinuteRate
          tags:
            cache: $1
            reason: $2
      - include:
          domain: metrics
          bean_regex: .*cachePuts\.cache\.(.*)\.cacheManager\.cacheManager.*
          attribute:
            OneMinuteRate:
              alias: customjmx.cachePuts.OneMinuteRate
          tags:
            cache: $1
      - include:
          domain: metrics
          bean_regex: .*cacheSize\.cache\.(.*)\.cacheManager\.cacheManager.*
          attribute:
            Value:
              alias: customjmx.cacheSize
          tags:
            cache: $1
      - include:
          domain: metrics
          bean_regex: .*hikaricpConnectionsActive\.pool\.(.*)
          attribute:
            Value:
              alias: customjmx.hikaricpConnections.active
          tags:
            pool: $1
      - include:
          domain: metrics
          bean_regex: .*hikaricpConnectionsIdle\.pool\.(.*)
          attribute:
            Value:
              alias: customjmx.hikaricpConnections.idle
          tags:
            pool: $1
      - include:
          domain: metrics
          bean_regex: .*jvmThreadsStates\.state\.(.*)
          attribute:
            Value:
              alias: customjmx.jvmThreadStates.state.$1
      - include:
          domain: metrics
          bean_regex: .*tomcatThreadsBusy\.name\.(.*)
          attribute:
            Value:
              alias: customjmx.tomcatThreadsBusy
          tags:
            name: $1
      - include:
          domain: metrics
          bean_regex: .*tomcatThreadsCurrent\.name\.(.*)
          attribute:
            Value:
              alias: customjmx.tomcatThreadsCurrent
          tags:
            name: $1
```

This setup also includes some regex matching to pull out the name of the cache, pool its associated with, or the reason.  [Docs](https://docs.datadoghq.com/integrations/java/?tab=host#configuration)
