### ISSUE TITLE
JMX: runtime-id is blank when running on kubernetes

### ISSUE THREAD

**Issue by rarecrumb** [DataDog/jmxfetch#388]
Using pod annotations, the JMX integration is working, but `runtime-id` is blank on the default JMX dashboard.

```yaml
podAnnotations:
  ad.datadoghq.com/app.logs: '[{"source": "java", "service": "app"}]'
  ad.datadoghq.com/app.check_names: '["jmx"]'
  ad.datadoghq.com/app.init_configs: '[{"is_jmx": true, "collect_default_metrics": true, "new_gc_metrics": true, "service": "app"}]'
  ad.datadoghq.com/app.instances: '[{"host": "%%host%%", "port": "9010"}]'
```
